### ISSUE TITLE
The hash-histroy-basketball/articles keep showing error 500

### ISSUE THREAD

**Issue by thorai219** [uidotdev/react-router-v5-course#4] opened 2021-03-10 19:56 UTC
![Screenshot from 2021-03-10 11-55-05](https://user-images.githubusercontent.com/23511973/110689487-9680cb80-8197-11eb-9bd5-9657ca714f83.png)

**Comment by tylermcginnis** [comment] 2021-04-28 16:54
Can't reproduce so closing for now.

**Closed as completed by tylermcginnis** 2021-04-28 16:54 UTC
